services:
  frontend:
    build:
      context: ./apps/frontend # Nuevo path dentro del monorepo
      dockerfile: Dockerfile
    ports:
      - "10000:10000" # Ajusta según tu configuración
    volumes:
      - ./apps/frontend:/app # Apunta a la nueva ubicación
      - /app/node_modules # Evita sobrescribir node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/backend # Nuevo path dentro del monorepo
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
