version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "10000:10000" # Ajusta según el framework (React/Vite usa 5173, Next.js usa 3000)
    volumes:
      - .:/app
      - /app/node_modules # Evita que sobrescriba node_modules del contenedor
    environment:
      - CHOKIDAR_USEPOLLING=true # Permite detectar cambios en archivos dentro de Docker
